---
title: "Create input file from a DESeq2 object"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create input file}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

knitr::opts_chunk$set(dpi=300,
  dev = "svg",
  dpi = 300,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

library(knitr)
```


<!-- badges: start -->

<!-- badges: end -->



```{r, include=F}

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
library(DESeq2)
library(SummArIzeR)
```
```{r load_data, include= T}
data("example_data") 
example_data
summary(example_data)
```
The DESeq2 objects contains the different conditions as colnames and the genes as rownames. We can extract a results table for the different comparisons.

```{r create_table, include=T}
res <- results(example_data, contrast = c("Treatment", "IFNb", "untreated"))
head(res)
```

We can generate a comprehensive results dataframe by looping through each condition. We can optionally filter the results by log2 fold change `log2fold` and adjusted p-value `padj`.
 

```{r create_df, include=T}

condition_list<-c("IFNb", "IFNg", "IL17", "IL1b", "IL4")
counter<-0
for(cond in condition_list){
  counter<-counter + 1
  res_i <- results(example_data, contrast = c("Treatment", cond, "untreated"))%>% 
     as.data.frame() %>%
  tibble::rownames_to_column("gene") %>%
  dplyr::select(gene, log2FoldChange, padj) %>%
  dplyr::mutate(comparison = str_glue(cond,"_vs_untreated")) %>%
  dplyr::rename(log2fold = log2FoldChange)
 if(counter == 1){res<-res_i}
if(counter >1){res<-rbind(res, res_i)}  
  
}
# Filter signifiant results

res_df_signif<-res %>% dplyr::filter(is.na(log2fold) ==F & is.na(padj) == F & abs(log2fold)>1 & padj<= 0.05)
head(res_df_signif)
```